import Head from 'next/head';
import Header from '@src/components/Header';

const Layout = ({ children }) => {
  return (
    <div className=''>
      <Head>
        <title>Kulture: Home of beats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Header />
      </header>
      <main>{children}</main>
      <footer></footer>
    </div>
  );
};

export default Layout;
