import Head from 'next/head';
import Header from '@src/components/Header';
import Footer from '@src/components/Footer';

const Layout = ({ children, styles, page }) => {
  console.log('layout', page);
  return (
    <div className=''>
      <Head>
        <title>Kulture: Home of beats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Header page={page} />
      </header>
      <main className={styles}>{children}</main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Layout;
